schedules:
  - cron: "0 5 * * *"
    displayName: "Deploy em produção todo dia às 2am"
    branches:
      include:
        - master
      exclude:
        - dev
        - mario
        - parceiro_funcionario
        - testes

pool:
  vmImage: "ubuntu-latest"
strategy:
  matrix:
    node_8_x:
      node_version: 8.16.1

steps:
  - script: sudo npm install -g mup
    displayName: "Instalando o MUP"
  - script: |
      echo "Instalando o Meteor"
      curl https://install.meteor.com/ | sh
      export PATH=$PATH:$HOME/.meteor
      echo "Instalando as dependências do projeto"
      meteor npm install
      echo "Configurando o mup"
      cd .deploy
      mup setup
      echo "Iniciando o deploy"
      mup deploy
      echo "Deploy finalizado"
